# Do **not** use this yml for production.
# This is only for the dev environment
# SankalpSocial - Docker Alpine Build Configuration

services:
  sankalpsocial-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: sankalpsocial-app
    restart: always
    environment:
      DATABASE_URL: postgresql://sankalpsocial-local:sankalpsocial-local-pwd@sankalpsocial-postgres:5432/sankalpsocial-db-local
      REDIS_URL: redis://sankalpsocial-redis:6379
      JWT_SECRET: dev-jwt-secret-change-in-production
      MAIN_URL: http://localhost:4200
      FRONTEND_URL: http://localhost:4200
      NEXT_PUBLIC_BACKEND_URL: http://localhost:3000
      BACKEND_INTERNAL_URL: http://localhost:3000
      STORAGE_PROVIDER: local
      UPLOAD_DIRECTORY: /app/uploads
      NEXT_PUBLIC_UPLOAD_STATIC_DIRECTORY: uploads
      BACKEND_PORT: 3000
      FRONTEND_PORT: 4200
    ports:
      - 4200:5000
      - 3000:3000
    volumes:
      - uploads-volume:/app/uploads
    depends_on:
      - sankalpsocial-postgres
      - sankalpsocial-redis
    networks:
      - sankalpsocial-network
  sankalpsocial-postgres:
    # ref: https://hub.docker.com/_/postgres
    image: postgres:17-alpine # 17.0
    container_name: sankalpsocial-postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: sankalpsocial-local-pwd
      POSTGRES_USER: sankalpsocial-local
      POSTGRES_DB: sankalpsocial-db-local
    volumes:
      - postgres-volume:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - sankalpsocial-network
  sankalpsocial-redis:
    # ref: https://hub.docker.com/_/redis
    image: redis:7-alpine # 7.4.0
    container_name: sankalpsocial-redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - sankalpsocial-network
  sankalpsocial-pg-admin:
    # ref: https://hub.docker.com/r/dpage/pgadmin4/tags
    image: dpage/pgadmin4:latest
    container_name: sankalpsocial-pg-admin
    restart: always
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    networks:
      - sankalpsocial-network
  sankalpsocial-redisinsight:
    # ref: https://hub.docker.com/r/redis/redisinsight
    image: redis/redisinsight:latest
    container_name: sankalpsocial-redisinsight
    links:
      - sankalpsocial-redis
    ports:
      - '5540:5540'
    volumes:
      - redisinsight:/data
    networks:
      - sankalpsocial-network
    restart: always

volumes:
  redisinsight:
  postgres-volume:
    external: false
  uploads-volume:
    external: false

networks:
  sankalpsocial-network:
    external: false
